import {
  IconAlertTriangle,
  IconArrowRight,
  IconArrowLeft,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconChevronsDown,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconPhotoUp,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconLogout,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconCalendar,
  IconTag,
  IconMap,
  IconHome,
  IconTarget,
  IconFlag,
  IconShare,
  IconBrandFacebook,
  IconBrandInstagram,
  IconMessageCircle,
  IconBell,
  IconEdit
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronsDown: IconChevronsDown,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  image: IconPhoto,
  gallery: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  users: IconUsers,
  arrowRight: IconArrowRight,
  arrowLeft: IconArrowLeft,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  facebook: IconBrandFacebook,
  instagram: IconBrandInstagram,
  check: IconCheck,
  calendar: IconCalendar,
  tag: IconTag,
  map: IconMap,
  home: IconHome,
  'shopping-bag': IconShoppingBag,
  target: IconTarget,
  flag: IconFlag,
  share: IconShare,
  messageCircle: IconMessageCircle,
  bell: IconBell,
  creditCard: IconCreditCard,
  logout: IconLogout,
  photoUp: IconPhotoUp,
  edit: IconEdit,
  file: IconFile
};
